### PR TITLE
Polymer 3 2019 01 29 100646

### PR DESCRIPTION
**Pull request by awikkerink**

### CODE REVIEW

**Comment by mtjandra** [comment]
Hey I am not familiar with what to look out for during Polymer 3 conversion. Unsure if a different reviewer makes sense, or if we trust the tool such that there isn't much to be looking for. (Similar to when we do line changes or something like that)

**Comment by awikkerink** [comment]
@mtjandra  Could you also merge?

**Comment by mtjandra** [comment]
That is weird, it looks like you should have write perms, I'll double check

image

**Comment by mtjandra** [comment]
Not sure everything seems to look fine, but I will merge for you

**Comment by awikkerink** [comment]
I was able to create the polymer 3 upgrade branch, but I wasn't able to merge to master for some reason, even after you approved.

**Pull request merged**
