### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by awikkerink**

### CODE REVIEW

**Comment by neverendingqs** [comment]
I see GitHub already has a 2.0.0 release. Do we need to recreate that release?

**Comment by awikkerink** [comment]
The tag points to a revision with no version in the package.json file, which npm doesn't like. So, I can either add a new tag or remove/recreate the old one. I think it's simpler to just create a new patch version.

**Comment by awikkerink** [comment]
I'm also not authorized to merge to master.

**Comment by neverendingqs** [comment]
I can merge.

https://travis-ci.org/Brightspace/d2l-my-dashboards-ui/builds/488544665 seems to be stuck on sauce connect. Do we need to wait for that to finish?

**Comment by awikkerink** [comment]
Not necessarily. It'll just timeout. The tests have run an passed before.

**Pull request merged**
